version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: fuever
      POSTGRES_PASSWORD: fuever
      POSTGRES_USER: fuever
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
