version: '3.1'

services:

  db:
    image: postgres
    container_name: fuever_db
    restart: always
    environment:
      POSTGRES_DB: fuever
      POSTGRES_PASSWORD: fuever
      POSTGRES_USER: fuever
    volumes:
      - fuever_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2
    container_name: fuever_cache
    restart: always
    ports:
      - "6379:6379"
  
  golang:
    # build: 
    #   context: .
    #   dockerfile: dockerfile
    image: avaqua/fuever:latest
    container_name: fuever_go
    restart: always
    environment:
      - EMAIL_MAILBOX=${EMAIL_MAILBOX}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - COS_BUCKET_URL=${COS_BUCKET_URL}
      - COS_SECRET_ID=${COS_SECRET_ID}
      - COS_SECRET_KEY=${COS_SECRET_KEY}
    ports:
      - "8080:8080"
    command: ./boot
    depends_on:
      - db
      - cache