name: Test
on: [ push ]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
      FUEVER_GO: fuever_go
      FUEVER_DB: localhost
      FUEVER_CACHE: localhost
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: fuever
          POSTGRES_USER: fuever
          POSTGRES_PASSWORD: fuever
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install dependencies
        run: go get ./...

      - name: Add Test Model
        run: go get -t ./...

      - name: Build
        run: go build -v ./...

      - name: Test with the Go CLI
        run: go test -v ./...